# -*- coding: utf-8 -*-
"""ximena paltea2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CBIF1mwbBxUte2Ssnu0KLD190s-z7DC9
"""

import streamlit as st
import pandas as pd
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import gdown
import os

# El binomio de oro a vuelto jijij
